%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera1.input: /usb_cam/image_raw
# save as photo
Camera1.outputx: ../config/weightx.png
Camera1.outputy: ../config/weighty.png

Camera1.setHeight: 0.3 # 米
Camera1.setAngle: 0 # 度

# 相机内参
Camera1.fx: 768.6145
Camera1.fy: 769.0561
Camera1.cx: 681.7078
Camera1.cy: 372.4581

# distortion parameters
Camera1.k1: 0.1105
Camera1.k2: -0.1373
Camera1.p1: 0.0005
Camera1.p2: -0.0013
Camera1.k3: 0.0178

# Camera resolution
Camera1.width: 1280
Camera1.height: 720

# Camera frames per second 
Camera1.fps: 60

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera1.RGB: 1